### PR TITLE
Redacted fields 

### PR DESCRIPTION
**Pull request by honnix**
Add `AutoMatter.Sensitive` annotation to mark a field to be sensitive so that the value of it will be substituted by `****` (default) or any provided string in generated `toString()`.

### CODE REVIEW

**Comment by honnix** [comment]
@danielnorberg Wdyt of this?

**Comment by honnix** [comment]
CI doesn't seem to run for a fork. I verified locally.

**Comment by danielnorberg** [comment]
Seems useful but maybe we could call it redacted instead? See https://immutables.github.io/immutable.html#redacted-attributes

**Comment by honnix** [comment]
Yeah that sounds better. I was struggling to find a suitable word. Thanks for the pointer.

**Pull request merged**
