### PR TITLE
Add nullable to builder

### PR DESCRIPTION
**Pull request by vincentbrison**
This PR add `@Nullable` to builder setter of `@Nullable` field.

### CODE REVIEW

**Comment by danielnorberg** [comment]
This seems like a useful change, thanks for the PR!

Auto-matter currently allows the use of any `@Nullable` annotation, not only `javax.annotation.Nullable`. I.e., `android.support.annotation.Nullable` or `foobar.Nullable` etc is also usable.

When adding the nullable annotation to the builder setter, we should perhaps use the same annotation type as was used on the field declaration in the interface instead of always using `javax.annotation.Nullable`.

What do you think?

**Comment by vincentbrison** [comment]
Yes you are right, I will change that and update the PR then (I am new with
JavaPoet, using Nullable from javax was the easiest way to do it at the
time I did that).

Le 13 avr. 2017 2:06 PM, "Daniel Norberg" <notifications@github.com> a
écrit :

**Comment by danielnorberg** [comment]
👍

**Comment by danielnorberg** [comment]
Maybe something like this? 

https://github.com/danielnorberg/auto-matter/commit/76dc0d2f99158f8a3eb5eb26a3a4c797296ddc7a

**Comment by vincentbrison** [comment]
Looks good 🙂 !

Le 13 avr. 2017 2:18 PM, "Daniel Norberg" <notifications@github.com> a
écrit :

**Pull request merged**
