### PR TITLE
Add merge method.

### PR DESCRIPTION
**Pull request by gilles**
I realized this sort of sucks while making it as this only works for non primitives.

Not sure you want to pull this in but it was nice looking at how generators work anyway.

### CODE REVIEW

**Comment by danielnorberg** [comment]
Could also be the case that null has been explicitly assigned to a field of the `other` builder, so we don't really know if any field on the `other` builder with a "default" value has been assigned to or not.

Accepting the above caveat, we could generalize the merge method to say that `this` builder receives all non-default valued fields from the `other` builder, including primitives.

It's still a method with potentially surprising behavior though. I'm curious about the use case and whether there are more users out there with the same use case and need.

**Comment by gilles** [comment]
My use case is that I fetch data from 3 different downstream services, each of them having a different schema (A, B, C)

Then I have some merger logic to merge the 3 sources into a new schema (N), some fields only exists in one source, some other in two sources, one overriding the other.

The merger takes (A, B, C) as input and outputs N. I though by having the `merge` method directly in automatter I could have an adapter to transform A -> N, B -> N, C -> N then my merge logic becomes straightforward, just apply `merge` in order.

Now thinking about my logic I can't even use this because one of the field is not just an "override" or "default" type, it's a real merge of two `List` fields so that would not even work.

I'm less and less convinced this is a good idea after all.

**Comment by danielnorberg** [comment]
Is this still relevant or can we close it?

**Comment by gilles** [comment]
We can close it

**Pull request closed without merging**
